[profile.default]
  evm_version = "paris"
  fs_permissions = [{ access = "read", path = "./zkout" }]
  libs = ["lib"]
  out = "out"
  remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  ]
  src = "src"

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "multi"
  tab_width = 2
  wrap_comments = true
